In [29]:
import torch
from torch.utils.data import Dataset
import numpy as np
from pathlib import Path
import os

import csv
from data_generation import getDataset, A, B, C, get_data_and_query_list, get_data_and_query_list_classification
from tabnet_nn import TabNetClass

import sys
sys.path.append('../')
sys.path.append('../tabnet/')
import torch
from tabnet.pytorch_tabnet.tab_model import TabNetClassifier

In [30]:
cat_idxs, cat_dims, X_train, y_train, X_test, y_test, X_valid, y_valid = getDataset()
# train_im = (train_im - train_im_mean) / (train_im_std + std_eps)
# test_im = (test_im - train_im_mean) / (train_im_std + std_eps)
std_eps = 1e-7
# mean = 13663371
# std = 432617472
# mean = np.array([13957.98828125, 13745.662109375, 13167.2392578125, 13569.68359375, 13949.2998046875, 13651.0263671875, 14229.9130859375, 13707.5029296875, 13638.5478515625, 13973.296875, 13208.11328125, 13414.619140625, 13221.68359375, 13849.091796875])
# std = np.array([56801.58203125, 59977.14453125, 52696.41015625, 55285.53515625, 55181.80078125, 56164.78125, 58817.890625, 57530.44921875, 56601.30859375, 54942.81640625, 54631.1953125, 51787.45703125, 59670.05078125, 56394.84375])
mean = np.mean(X_train, axis=0)
std = np.std(X_train, axis=0)
X_train_normalized = (X_train - mean) / (std + std_eps)
X_test_normalized = (X_test - mean) / (std + std_eps)
print(X_train_normalized.max())
print(X_train_normalized.min())
print(X_train.max())
print(X_train.min())
print(f'mean = {mean}')
print(f'std = {std}')

File already exists.
Pick the indeces at random and save these as the file for the future usage.
['train' 'train' 'train' ... 'train' 'train' 'test']
39 73
 State-gov 9
 Bachelors 16
 13 16
 Never-married 7
 Adm-clerical 15
 Not-in-family 6
 White 5
 Male 2
 2174 119
 0 92
 40 94
 United-States 42
 <=50K 2
Set 3
12.208180247896188
-4.687234513184198
1484705
0
mean = [2.16001988e+01 3.86833856e+00 1.90070309e+05 1.02918801e+01
 9.07431761e+00 2.61407600e+00 6.55008028e+00 1.44502638e+00
 3.66526493e+00 6.68552642e-01 6.49950302e+00 2.10180442e+00
 3.93903968e+01 3.66984097e+01]
std = [1.36873420e+01 1.45538642e+00 1.06046492e+05 3.86621842e+00
 2.58057349e+00 1.50703802e+00 4.22331326e+00 1.60381798e+00
 8.47475477e-01 4.70733478e-01 2.32651434e+01 1.01749545e+01
 1.21632046e+01 7.82943740e+00]


In [3]:
A_train = A(X_train_normalized, y_train)
A_test = A(X_test_normalized, y_test)
print(type(A_train))

data_generation.A


In [24]:
print(A_train[0][0])
print(A_train[0][1])
print(len(A_train[0][0]))
X_train_normalized[0]

tensor([ 0.8398,  1.4668, -1.0121, -0.3383,  1.1368, -0.4086, -0.6078, -0.9002,
         0.3923,  0.7037, -0.2780, -0.2039, -2.2536,  0.2920],
       dtype=torch.float64)
0
14


array([ 0.83717175,  1.46359766, -1.01201848, -0.33905836,  1.13665943,
       -0.40861388, -0.60658108, -0.90002736,  0.39246116,  0.70261754,
       -0.27988366, -0.20426352, -2.25120837,  0.29130398])

In [5]:
print(len(A_train))
print(len(A_test))

26117
3225


In [6]:
mark = 'train'
data_file = Path(os.getcwd()+'/data/'+mark+'_data.txt')
with open(data_file, 'w') as f:
    if len(dummy) % 2 == 1:
        n = len(dummy)-1
    else: 
        n = len(dummy)
    for i in np.arange(0, n, 2):
        f.write(str(i)+' '+str(dummy[i]['X'][9])+' '+str(i+1)+' '+str(dummy[i+1]['X'][9]))
        f.write('\n')

In [16]:
train_loader = torch.utils.data.DataLoader(A_test, batch_size=100, shuffle=True)
test_loader = torch.utils.data.DataLoader(A_test, batch_size=100, shuffle=True)
for data, target in test_loader:
    print(type(data))
    print(type(target))
    break

<class 'torch.Tensor'>
<class 'torch.Tensor'>


In [17]:
train_dataset = B(dataset=A_train, examples='data/train_data.txt')
print(type(train_dataset))

data_generation.B


In [18]:
print(A_train[2])
dataList, queryList = get_data_and_query_list_classification(A_train)
# print(torch.nn.Softmax(A_train[2], dim=1))
# print(torch.tensor(A_train[2][0]).softmax())
# print(A_train[2][0].softmax())
print(torch.nn.Softmax(dim=0)(torch.randn(10, requires_grad=True)))
# print(train_dataset[49])
print(dataList)

(tensor([ 0.9867,  1.4668,  0.1894,  0.1797, -0.4212, -0.4086, -0.6078, -0.9002,
         0.3923,  0.7037, -0.2780, -0.2039,  0.3775,  0.2920],
       dtype=torch.float64), 1)
tensor([0.1475, 0.0861, 0.1352, 0.1258, 0.0442, 0.0389, 0.0330, 0.0316, 0.1958,
        0.1617], grad_fn=<SoftmaxBackward>)
[{'p': tensor([ 0.8398,  1.4668, -1.0121, -0.3383,  1.1368, -0.4086, -0.6078, -0.9002,
         0.3923,  0.7037, -0.2780, -0.2039, -2.2536,  0.2920],
       dtype=torch.float64)}
 {'p': tensor([-0.0416,  0.0919,  0.2465,  0.1797, -0.4212, -1.7359, -0.1342, -0.2779,
         0.3923,  0.7037, -0.2780, -0.2039, -0.0336,  0.2920],
       dtype=torch.float64)}
 {'p': tensor([ 0.9867,  1.4668,  0.1894,  0.1797, -0.4212, -0.4086, -0.6078, -0.9002,
         0.3923,  0.7037, -0.2780, -0.2039,  0.3775,  0.2920],
       dtype=torch.float64)}
 ...
 {'p': tensor([ 1.0601,  0.0919,  1.2567,  0.4387,  1.5263, -0.4086, -0.6078, -0.9002,
         0.3923,  0.7037, -0.2780, -0.2039, -0.0336,  0.2920],
       d

In [19]:
dataList, queryList = get_data_and_query_list(train_dataset)

In [20]:
print(queryList[123])
print(dataList[123])
print(dataList[123]['p1'].shape)

:- not wealth_gap(p1,0,p2,1).
{'p1': tensor([-0.1884,  0.0919, -1.1361,  1.2158, -0.0317, -1.7359, -1.3182,  1.5893,
        -1.9825, -1.4210, -0.2780, -0.2039, -0.0336,  0.2920],
       dtype=torch.float64), 'p2': tensor([-0.1884, -1.2831,  1.8347, -0.3383,  1.1368, -1.7359, -1.3182,  1.5893,
         0.3923, -1.4210, -0.2780, -0.2039, -0.4447, -2.6524],
       dtype=torch.float64)}
torch.Size([14])


# Test TabNet wrapper class

In [25]:
clf = TabNetClass(cat_idxs=cat_idxs, cat_dims=cat_dims)

In [26]:
tmp = []
for batch in train_loader:
    print(batch[0])
    tmp = batch[0]
    break

tensor([[-0.2619,  1.4668,  0.3855,  ..., -0.2039, -0.0336,  0.2920],
        [ 1.2805,  1.4668, -0.9982,  ..., -0.2039, -0.0336,  0.2920],
        [-0.7760,  0.0919, -0.0438,  ..., -0.2039,  1.1176,  0.2920],
        ...,
        [-0.2619,  0.0919, -1.4046,  ..., -0.2039, -0.8558,  0.2920],
        [ 0.1053,  0.7793, -0.1335,  ..., -0.2039,  0.8709,  0.2920],
        [-0.4088,  1.4668,  0.0586,  ..., -0.2039,  0.3775,  0.2920]],
       dtype=torch.float64)


In [27]:
print(clf(tmp, sparsity_loss=False))

IndexError: index out of range in self

In [28]:
print(type(clf))

<class 'tabnet_nn.TabNetClass'>


In [7]:
# Python3 code to demonstrate working of 
# Check if string contains any number
# Using isdigit() + any()
  
# initializing string
test_str = 'geeks4geeks'
  
# printing original string
print("The original string is : " + str(test_str))
  
# using any() to check for any occurrence
res = any(chr.isdigit() for chr in test_str)
      
# printing result 
print("Does string contain any digit ? : " + str(res)) 

if any(chr.isdigit() for chr in test_str):
    print('Yeap! It wörks!')

The original string is : geeks4geeks
Does string contain any digit ? : True
Yeap! It wörks!


In [74]:
import torchvision.transforms as transforms
train_loader = torch.utils.data.DataLoader(A_train,
                                           batch_size=100,
                                           shuffle=True)
loader = torch.utils.data.DataLoader(train_loader, batch_size=len(train_loader), num_workers=1)
num_of_pixels = len(train_loader) * 14
col_num = np.arange(14)
mean_vec = []
std_vec = []
for c in col_num:
    total_sum = 0
    # print(f'Column number {c}')
    for batch in train_loader:
        total_sum += batch[0][c].sum()
    mean = total_sum / num_of_pixels
    mean_vec.append(float(mean))
    # print(f'\t mean = {mean}')
    sum_of_squared_error = 0
    for batch in train_loader: 
        sum_of_squared_error += ((batch[0][c] - mean).pow(2)).sum()
    std = torch.sqrt(sum_of_squared_error / num_of_pixels)
    std_vec.append(float(std))
    # print(f'\t std = {std}')
print(mean_vec)
print(std_vec)

[13957.98828125, 13745.662109375, 13167.2392578125, 13569.68359375, 13949.2998046875, 13651.0263671875, 14229.9130859375, 13707.5029296875, 13638.5478515625, 13973.296875, 13208.11328125, 13414.619140625, 13221.68359375, 13849.091796875]
[56801.58203125, 59977.14453125, 52696.41015625, 55285.53515625, 55181.80078125, 56164.78125, 58817.890625, 57530.44921875, 56601.30859375, 54942.81640625, 54631.1953125, 51787.45703125, 59670.05078125, 56394.84375]


In [29]:
import torchvision.transforms as transforms
train_loader = torch.utils.data.DataLoader(A_train,
                                           batch_size=1024,
                                           shuffle=True
                                           ))

TypeError: __init__() got an unexpected keyword argument 'transforms'

In [69]:
2e-2

0.02

In [70]:
0.01

0.01

In [77]:
print(clf.network.batch_size)

AttributeError: 'TabNet' object has no attribute 'batch_size'

In [6]:
train_dataset = C(dataset=A_train, examples='data/classification_train_data.txt')
test_dataset = C(dataset=A_test, examples='data/classification_test_data.txt')
dataList, queryList = get_data_and_query_list_classification(train_dataset)

In [7]:
print(queryList)
print(len(queryList))

[':- not wealthy(p,0).' ':- not wealthy(p,0).' ':- not wealthy(p,0).' ...
 ':- not wealthy(p,1).' ':- not wealthy(p,0).' ':- not wealthy(p,0).']
25978


In [8]:
print(dataList)

[{'p': tensor([   33,     6, 83311,     9,    12,     2,     4,     0,     4,     1,
            0,     0,    12,    39], dtype=torch.int32)}
 {'p': tensor([    21,      4, 215646,     11,      8,      0,      6,      1,      4,
             1,      0,      0,     39,     39], dtype=torch.int32)}
 {'p': tensor([    36,      4, 234721,      1,      6,      2,      6,      0,      2,
             1,      0,      0,     39,     39], dtype=torch.int32)}
 ...
 {'p': tensor([     8,      2, 514716,      9,     12,      4,      1,      3,      2,
             0,      0,      0,     39,     39], dtype=torch.int32)}
 {'p': tensor([     3,      4, 270436,     11,      8,      4,      7,      3,      4,
             1,      0,      0,     39,     39], dtype=torch.int32)}
 {'p': tensor([   29,     4, 42972,    12,    13,     2,    10,     5,     4,     0,
            0,     0,    21,    39], dtype=torch.int32)}]


In [78]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"
dataset_name = 'census-income'
data_file = Path(os.getcwd()+'/data/'+dataset_name+'.csv')
data_file.parent.mkdir(parents=True, exist_ok=True)
if data_file.exists():
    print("File already exists.")
else:
    print("Downloading file...")
    wget.download(url, data_file.as_posix())
# 2. Load the data and split accordingly
train = pd.read_csv(data_file)
target = ' <=50K'
if "Set" not in train.columns:
    train["Set"] = np.random.choice(["train", "valid", "test"], p =[.8, .1, .1], size=(train.shape[0],))
train_indices = train[train.Set=="train"].index
valid_indices = train[train.Set=="valid"].index
test_indices = train[train.Set=="test"].index
# 3. Label encode categorical features and fill empty cells.
nunique = train.nunique()
types = train.dtypes
categorical_columns = []
categorical_dims =  {}
for col in train.columns:
    if types[col] == 'object' or nunique[col] < 200:
        print(col, train[col].nunique())
        l_enc = LabelEncoder()
        train[col] = train[col].fillna("VV_likely")
        train[col] = l_enc.fit_transform(train[col].values)
        categorical_columns.append(col)
        categorical_dims[col] = len(l_enc.classes_)
    else:
        train.fillna(train.loc[train_indices, col].mean(), inplace=True)
# 4. Define categorical features for categorical embeddings
unused_feat = ['Set']
features = [ col for col in train.columns if col not in unused_feat+[target]] 
cat_idxs = [ i for i, f in enumerate(features) if f in categorical_columns]
cat_dims = [ categorical_dims[f] for i, f in enumerate(features) if f in categorical_columns]
# 5. Define the data subsets.
X_train = train[features].values[train_indices]
y_train = train[target].values[train_indices]
X_test = train[features].values[test_indices]
y_test = train[target].values[test_indices]
X_valid = train[features].values[valid_indices]
y_valid = train[target].values[valid_indices]

File already exists.
39 73
 State-gov 9
 Bachelors 16
 13 16
 Never-married 7
 Adm-clerical 15
 Not-in-family 6
 White 5
 Male 2
 2174 119
 0 92
 40 94
 United-States 42
 <=50K 2
Set 3


In [79]:
train["Set"]

0        1
1        1
2        1
3        1
4        1
        ..
32555    0
32556    1
32557    2
32558    2
32559    1
Name: Set, Length: 32560, dtype: int64

In [115]:
import os
from pathlib import Path
indices_file = Path(os.getcwd()+'/data/indices.npy')
indices_file.parent.mkdir(parents=True, exist_ok=True)
indices = []
if indices_file.exists():
    print("File already exists. Load the indices...")    
    indices = np.load(indices_file)
else:    
    print("Pick the indeces at random and save these as the file for the future usage.")
    indices = np.random.choice(["train", "valid", "test"], p =[.8, .1, .1], size=(train.shape[0],))
    np.save(indices_file, indices)
print(indices)

File already exists. Load the indices...
['valid' 'train' 'train' ... 'valid' 'train' 'train']


In [116]:
indeces[0:3]

array(['train', 'test', 'train'], dtype='<U5')

In [111]:
indeces_file = Path(os.getcwd()+'/data/indices.npy')
array = np.load(indeces_file)

In [112]:
array

array([], dtype='<U5')